myNextApplication:
  component: '@sls-next/serverless-component@3.1.0'
  inputs:
    bucketRegion: ap-northeast-1
    bucketName: ${env.BUCKET_NAME}
    runtime:
      defaultLambda: 'nodejs14.x'
      apiLambda: 'nodejs14.x'
      imageLambda: 'nodejs14.x'
    memory:
      defaultLambda: 1024
      apiLambda: 512
      imageLambda: 512
    name:
      defaultLambda: ${env.LAMBDA_NAME}
      apiLambda: ${env.API_LAMBDA_NAME}
      imageLambda: ${env.IMAGE_LAMBDA_NAME}
    cloudfront:
      distributionId: ${env.DISTRIBUTION_ID}
    roleArn: ${env.ROLE_ARN}
